#!/bin/bash

### BEGIN INIT INFO
# Provides:       flapper
# Required-Start: $syslog $remote_fs redis-server
# Required-Stop:  $syslog $remote_fs redis-server
# Should-Start:   $local_fs
# Should-Stop:    $local_fs
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:  flapjack - scalable monitoring notification system
# Description:    flapjack - scalable monitoring notification system
### END INIT INFO

PATH=/opt/flapjack/bin:$PATH

if ! type flapjack > /dev/null 2>&1; then
  echo "Error: flapjack isn't in PATH."
  echo "Refusing to do anything!"
  exit 1
fi

# Evaluate command
flapjack flapper $1

RETVAL=$?
exit $RETVAL
