#!/bin/bash
# vim: ft=sh:et:ts=4:sw=4:sts=4:

CWD=$(pwd)

rm -rf flapjack/opt/flapjack/{vendor,.bundle,bin} || true

cd flapjack/opt/flapjack || exit 
bundle install --without development --path vendor/bundle --binstubs bin || exit

cd "$CWD" || exit
cd flapjack/opt/flapjack/vendor/bundle/ruby/*/gems/flapjack-[0-9]* || exit
if [ ! -d "src" ]; then
    git pull
fi

export GOPATH
GOPATH=$(pwd)
./build.sh
rm -rf src/*

cd "$CWD" || exit
cd flapjack || exit
#find . -type d -name '*.git'|xargs rm -rf
find . -type f ! -regex '.*.git.*' ! -regex '.*?debian-binary.*' ! -regex '.*?DEBIAN.*' ! -regex '._.DS_Store' ! -regex '.DS_Store' -printf '%P ' | xargs md5sum > DEBIAN/md5sums

cd "$CWD" || exit
chmod 0755 flapjack/DEBIAN/{*rm,*inst}
fakeroot dpkg-deb -b flapjack flapjack_2.0.0_all.deb
rm -rf flapjack/opt/flapjack/{vendor,.bundle,bin}
cd "$CWD" || exit
