#!/bin/bash
#
# Perform necessary flapjack setup steps after package is installed.
#

INSTALLER_DIR=`dirname $0`
DEST_DIR=/opt/flapjack
CONFIG_DIR=/etc/flapjack
GEM_DIR=$DEST_DIR//vendor/bundle/ruby/*/
# FLAPJACK_GEM_DIR=`ls -dr ${DEST_DIR}/vendor/bundle/ruby/*/gems/flapjack-* | tail -1`
PROGNAME=$(basename $0)
INITDDIR="/etc/init.d"

groupadd flapjack
useradd --system --gid flapjack --no-create-home flapjack

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# Set up config + logging directories
mkdir -p /etc/flapjack /var/log/flapjack /var/run/flapjack /var/lib/flapjack/redis-flapjack
chown -R flapjack:flapjack /var/log/flapjack /var/run/flapjack /var/lib/flapjack

# if [ ! -e /etc/flapjack/flapjack_config.toml ] ; then
#   echo "Creating /etc/flapjack/flapjack_config.toml"
#   cp ${FLAPJACK_GEM_DIR}/etc/flapjack_config.toml.example ${CONFIG_DIR}/flapjack_config.toml
# fi

# for version in 3 4 ; do
#   if [ ! -e /usr/local/lib/flapjackfeeder${version}.o ] ; then
#     echo "Creating /usr/local/lib/flapjackfeeder${version}.o for Nagios ${version}"
#     cp ${FLAPJACK_GEM_DIR}/flapjackfeeder${version}.o /usr/local/lib/flapjackfeeder${version}.o
#   fi
# done

if [ ! -e /usr/local/lib/flapjackfeeder.o ] ; then
  echo "Symlinking the Nagios version 3 flapjackfeeder to /usr/local/lib/flapjackfeeder.o for backwards compatibility"
  ln -s /usr/local/lib/flapjackfeeder3.o /usr/local/lib/flapjackfeeder.o
fi

#if [ ! -e ${INITDDIR}/redis-flapjack ] ; then
#  echo "Creating ${INITDDIR}/redis-flapjack"
#  chmod u+x ${INITDDIR}/redis-flapjack
#fi

if [ ! -e ${INITDDIR}/flapjack ] ; then
  echo "Creating ${INITDDIR}/flapjack"
  chmod u+x ${INITDDIR}/flapjack
fi

if [ ! -e ${INITDDIR}/flapper ] ; then
  echo "Creating ${INITDDIR}/flapper"
  chmod u+x ${INITDDIR}/flapper
fi

echo "Setting paths"
if [ ! -e /etc/profile.d/flapjack.sh ] ; then
  cat > /etc/profile.d/flapjack.sh <<'EOF'
PATH=$PATH:/opt/flapjack/bin
GEM_PATH=/opt/flapjack/vendor/bundle/ruby/*/
EOF
  chmod 644 /etc/profile.d/flapjack.sh
fi


update-rc.d redis-server defaults 94 06 >/dev/null || exit $?
update-rc.d flapjack defaults 95 05 >/dev/null || exit $?
echo "Starting redis"
${INITDDIR}/redis-server start || exit $?

echo "Starting flapjack"
${INITDDIR}/flapjack start || exit $?

echo "Thank you for installing flapjack!"
echo
echo "Log in again to have /opt/flapjack/bin added to your PATH or run:"
echo "  export PATH=$PATH:/opt/flapjack/bin"
echo

echo "Flapjack should now be running. Visit http://localhost:3080/"

exit 0
