#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	userdel flapjack || true
	update-rc.d flapjack remove >/dev/null
	rm -f /etc/redis/redis.conf
	dpkg-divert --rename --remove /etc/redis/redis.conf
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
