#!/bin/sh

if [ -f /usr/local/lib/flapjackfeeder.o ]
then
	unlink /usr/local/lib/flapjackfeeder.o
fi

if [ -f /etc/redis/redis.conf ]
then
	dpkg-divert --add --rename --divert /etc/redis/redis.conf.disabled /etc/redis/redis.conf
fi
